---
# personal_workstation_setup/tasks/main.yml

- name: 'Load variables'
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', parameters) }}"
  vars:
    parameters:
      files:
        - "vars_{{ ansible_distribution | regex_replace(' ', '_') }}_{{ ansible_distribution_version }}.yml"
        - "vars_{{ ansible_distribution | regex_replace(' ', '_') }}_{{ ansible_distribution_major_version }}.yml"
        - "vars_{{ ansible_distribution | regex_replace(' ', '_') }}.yml"
        - "vars_{{ ansible_os_family | regex_replace(' ', '_') }}.yml"
      paths:
        - ../vars/
  tags:
    - distribution_packages
    - flatpak
    - installation
    - opensuse

- name: 'Flatpak related tasks'
  ansible.builtin.import_tasks: flatpak.yml
  tags:
    - flatpak
    - installation

- name: 'RPM installation on openSUSE Tumbleweed or MicroOS'
  ansible.builtin.import_tasks: opensuse.yml
  when:
    - ansible_os_family == "Suse"
    - ansible_distribution == "openSUSE Tumbleweed"
      or ansible_distribution == "openSUSE MicroOS"
  tags:
    - opensuse
    - distribution_packages
    - installation
