---
# personal_workstation_setup/tasks/opensuse.yml

#
# Tumbleweed with zypper, not transactional-update
#

- name: 'Uninstall packages via zypper without a reboot'
  community.general.zypper:
    name: "{{ distribution_packages_to_remove }}"
    state: absent
  become: true
  when:
    - ansible_distribution == "openSUSE Tumbleweed"
      or ansible_distribution == "openSUSE Tumbleweed-Slowroll"

- name: 'Install packages via zypper without a reboot'
  community.general.zypper:
    name: "{{ distribution_packages }}"
    state: present
  become: true
  when:
    - ansible_distribution == "openSUSE Tumbleweed"
      or ansible_distribution == "openSUSE Tumbleweed-Slowroll"

- name: 'Install additional packages via zypper without a reboot'
  community.general.zypper:
    name: "{{ additional_distribution_packages }}"
    state: present
  become: true
  when:
    - ansible_distribution == "openSUSE Tumbleweed"
      or ansible_distribution == "openSUSE Tumbleweed-Slowroll"
    - additional_distribution_packages is defined

#
# Tumbleweed with transactional-update
#

- name: 'Uninstall packages via zypper with a reboot'
  community.general.zypper:
    name: "{{ distribution_packages_to_remove }}"
    state: absent
  become: true
  when:
    - ansible_distribution == "openSUSE MicroOS"

- name: 'Install packages via zypper with a reboot'
  community.general.zypper:
    name: "{{ distribution_packages }}"
    state: present
  become: true
  when:
    - ansible_distribution == "openSUSE MicroOS"

- name: 'Install additional packages via zypper with a reboot'
  community.general.zypper:
    name: "{{ additional_distribution_packages }}"
    state: present
  become: true
  when:
    - ansible_distribution == "openSUSE MicroOS"
    - additional_distribution_packages is defined
