---
# personal_workstation_setup/tasks/opensuse.yml

- name: 'Uninstall packages via zypper without a reboot'
  community.general.zypper:
    name: "{{ distribution_packages_to_remove }}"
    state: absent
  become: true
  when:
    - ansible_distribution == "openSUSE Tumbleweed"

- name: 'Install packages via zypper without a reboot'
  community.general.zypper:
    name: "{{ distribution_packages }}"
    state: present
  become: true
  when:
    - ansible_distribution == "openSUSE Tumbleweed"

- name: 'Uninstall packages via zypper with a reboot'
  community.general.zypper:
    name: "{{ distribution_packages_to_remove }}"
    state: absent
  become: true
  when:
    - ansible_distribution == "openSUSE MicroOS"

- name: 'Install packages via zypper with a reboot'
  community.general.zypper:
    name: "{{ distribution_packages }}"
    state: present
  become: true
  when:
    - ansible_distribution == "openSUSE MicroOS"
